[Task-2] Interfaces, Header, Footer
rogerosha/fe-react-2024 pull request #2
Opened 2024-04-27 22:26 UTC by rogerosha

**Acceptance criteria for 1**
- [ ] Mentor is added to pr
- [ ] AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  Interfaces for Product and Category based on [swagger](https://ma-backend-api.mocintra.com/docs#/categories/CategoriesController_getAll) are created and exported in separate file
- [ ] Static header and footer are created according to [mobile](https://www.figma.com/file/mRAOMdJiAsD8fHSVnYwUl9/React-web-page?type=design&node-id=13-17490&mode=design&t=3Thf45kJJYMoxsc0-0) and [desktop](https://www.figma.com/file/MIKTcyr6SvspkZnIQ5nEPD/MA-Courses-2022-2023?type=design&node-id=2471-2253&mode=design&t=4DJ0BIdFZZ4mUgAn-0) designs

**Acceptance criteria for 1***
- [ ] Shared component SocialIcon is created and used for footer icons
- [ ] Link to social network and path to icon are passed to component by the typed props

Deployed page: https://rogerosha.github.io/fe-react-2024/

Thanks! ✨

2024-04-29 08:31 UTC, KPIcoder reviewed
Fix the linter issues: 
https://github.com/rogerosha/fe-react-2024/actions/runs/8862994352/job/24363539248#step:6:17

Header should stretch to take up all the page width
<img width="1728" alt="Screenshot 2024-04-29 at 09 27 50" src="https://github.com/rogerosha/fe-react-2024/assets/97438530/203655a2-f6aa-47d2-8321-c70ad45e7aa2">

2024-04-29 08:31 UTC, KPIcoder commented on src/components/about/About.component.tsx
> +const MAlink = 'https://www.mastersacademy.education/frontend-for-beginners-it';
I recommend to move these social links to a separate file e.g `constants/socials.ts`. It will help you to follow DRY principle, so you can reuse the links at least here: https://github.com/rogerosha/fe-react-2024/pull/2/files#diff-c1716ec31957a41921dd20e6e007214fd8833e5d0bc59c47db461a88889caa28R4

2024-04-29 08:31 UTC, KPIcoder commented on src/components/header/Header.component.tsx
> +                <a href="#" className={styles['navigation-link']}>
The lint check fails here as it requires you to use the real value for the sake of accessibility. Learn more https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md

2024-04-29 08:31 UTC, KPIcoder commented on src/components/header/Header.component.tsx
> +                <a href="#" className={styles['navigation-link']}>
The lint check fails here as it requires you to use the real value for the sake of accessibility. Learn more https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md

2024-04-29 08:31 UTC, KPIcoder commented on src/types/interfaces.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Please do not disable eslint rules. They are meant to help you

2024-04-29 08:31 UTC, KPIcoder commented on src/types/interfaces.ts
Separate the interfaces. Create a file for each.

2024-04-29 08:31 UTC, KPIcoder commented on src/types/interfaces.ts
> +interface Product {
```suggestion
export interface Product {
```

2024-04-29 08:31 UTC, KPIcoder commented on src/types/interfaces.ts
> +interface Category {
```suggestion
export interface Category {
```

2024-04-29 09:56 UTC, KPIcoder commented on src/components/footer/Footer.component.tsx
> +                <a href="https://www.facebook.com">
Move these links to separate components according to the task

2024-04-29 23:02 UTC, rogerosha commented on src/components/about/About.component.tsx
> +const MAlink = 'https://www.mastersacademy.education/frontend-for-beginners-it';
I can't make a commit for now due to this issue:

![image](https://github.com/rogerosha/fe-react-2024/assets/71977925/86ffaf59-7aec-40cf-b050-22d0bed2a8c0)

2024-04-30 11:51 UTC, rogerosha commented
> Header should stretch to take up all the page width

can't fix it for now (it doesn't want to work), if you don't mind, I will fix it in the next hw 👀

2024-04-30 13:38 UTC, KPIcoder requested changes

2024-04-30 13:38 UTC, KPIcoder commented on src/components/socialIcon/SocialIcon.component.tsx
The idea of `SocialIcon` component is to create a reusable piece of code for which you can give a link and and an icon and it will return you a nice icon. Think about it as making small building blocks you would you to build a house. 

In our case we should have something like
```
interface Props {
    icon: string;
    link: string;
}

export const SocialIcon = ({ icon, link }: Props) => (
    <a href={link}>
        <img className={styles['social-icon']} src={icon} alt="social network icon"></img>
    </a>
);
```
You can reuse it later
```
// somewhere in the footer component
<SocialIcon link={facebookLink} icon="./facebook.svg" />
```

2024-04-30 22:44 UTC, rogerosha commented on src/components/socialIcon/SocialIcon.component.tsx
It took some time to understand the main point! 😄

2024-05-02 08:34 UTC, KPIcoder approved these changes

2024-05-02 08:34 UTC, merged