[Task-3] Components in React
rogerosha/fe-react-2024 pull request #3
Opened 2024-05-03 14:04 UTC by rogerosha

**Acceptance Criteria for 1**
- [ ] Mentor is added to pr
- [ ] AC copied to pr description
- [ ] Link to deployed version is added to pr
- [ ] The ProductsList component correctly receives product data as props.
- [ ] ProductCard component created and renders a single product.
- [ ] Header and Footer elements are present.
- [ ] ProductList displays right on mobile devices

**Acceptance Criteria for 1***
- [ ] The Header component has clickable elements that toggle the display between the About and ProductsList components.
- [ ] State management is handled in App.tsx, with state determining which component to show.
- [ ] LocalStorage added to save items in card after page reload

Thanks! ✨

2024-05-03 23:04 UTC, KPIcoder requested changes
- Fix the linter issues
- Extend the header on the About page to take all the width of the screen and stay consistent with the Products page
- Move your components that you use as pages to a separate folder `pages`

2024-05-03 23:04 UTC, KPIcoder commented on src/App.tsx
> +                const response = await fetch('https://ma-backend-api.mocintra.com/api/v1/products?limit=8&offset=2');
I like the fact that you went ahead of the course and used the data from the api for the products 👍
You will learn a better approach for data fetching on the lesson about Redux

2024-05-03 23:04 UTC, KPIcoder commented on src/App.tsx
> +export type Page = 'about' | 'products';
there is no clean way to declare your pages unless you learn one of the routing libraries. But for now please move this type to a separate file in the directory where you declare your types. Keep your `App.tsx` file as clean as possible

2024-05-03 23:04 UTC, KPIcoder commented on src/App.tsx
> +    const [products, setProducts] = useState([]);
do not forget to use the power of typescript
```suggestion
    const [products, setProducts] = useState<Product[]>([]);
```

2024-05-03 23:04 UTC, KPIcoder commented on src/App.tsx
> +            <HeaderComponent page={page} onPageClick={(newPage) => setPage(newPage)} />
Try to minimise the logic in the JSX even the simple one. Move `onPageClick` to a separate function with a good and clear name. It is a good practice as it makes your code easier to read

2024-05-03 23:09 UTC, KPIcoder commented on src/components/productsList/ProductsList.component.tsx
> +        {products.map((product, index) => (
As long as you don't have to remove / add new products you will not face any issues with using index as a key, but I will recommend to use `product.id` instead. 
```suggestion
        {products.map((product) => (
          <ProductCard key={product.id} product={product} />
```

2024-05-13 10:07 UTC, rogerosha commented
> * Use local storage to save data if you want to receive 1*

I tried to do my best, but can't handle this task 😢

2024-05-19 08:11 UTC, KPIcoder approved these changes

2024-05-19 08:11 UTC, merged