[Task-5] Hooks
rogerosha/fe-react-2024 pull request #5
Opened 2024-06-03 22:10 UTC by rogerosha

**Acceptance Criteria for 1**

- [ ]  Mentor is added to pr
- [ ] AC copied to pr description
- [ ] Link to deployed version is added to pr
- [ ] Simple Pagination component (without ...) is added and works correctly
- [ ] On the 1st page button Back should be disabled, same as button Forward on the last page
- [ ] Interaction with pagination should not change or break sorting and filtration.
- [ ] Category filter (multi-select) is added and works correctly
- [ ] Sorting input (single select) is added and works correctly
- [ ] Interaction with filter and sorter should reset pagination and move a user to the 1st page

**Acceptance Criteria for 1***

- [ ] Pagination component with ... is implemented according to [design](https://www.figma.com/design/mRAOMdJiAsD8fHSVnYwUl9/React-web-page?node-id=1-7667&t=vIBPXrxFdrcCGSep-4).
- [ ] Search input works correctly

Deployed page: https://rogerosha.github.io/fe-react-2024/

Thanks! ✨

2024-06-03 22:43 UTC, rogerosha commented
> About logic for changing theme and adding products to the cart using useContext

I tried to rewrite but it doesn't want to work right. I'll think how to do it right

2024-06-07 10:12 UTC, KPIcoder requested changes

2024-06-07 10:12 UTC, KPIcoder commented on src/App.tsx
For each context create a separate file and encapsulate its logic there

2024-06-07 10:12 UTC, KPIcoder commented on src/components/header/Header.component.tsx
use theme context to avoid props drilling

2024-06-07 10:12 UTC, KPIcoder commented on src/components/pagination/Pagination.component.tsx
> +        if (totalPages <= 3) {
do not introduce magic numbers in code. Always give them a meaningful name
```
const MAX_UNCOLLAPSED_PAGES_COUNT = 3
if(totalPages < MAX_UNCOLLAPSED_PAGES_COUNT)
...
```

2024-06-07 10:12 UTC, KPIcoder commented on src/components/pagination/Pagination.component.tsx
> +            switch (currentPage) {
Current switch/case statement misses the case when you're 2 steps away from the edge. See screenshot

<img width="281" alt="image" src="https://github.com/rogerosha/fe-react-2024/assets/97438530/96973945-58a4-464f-89d9-7cb2373719e0">

It has to be 1,2,3

Perhaps describing each case where and when we should place the three dots will be easier than describing each case depending on the page count

2024-06-07 10:12 UTC, KPIcoder commented on src/components/pagination/Pagination.component.tsx
> +            for (let index = 1; index <= totalPages; index++) {
you can create a helper function `range` to generate numbers in the given range. I think you might need it

2024-06-07 10:12 UTC, KPIcoder commented on src/components/searchBar/SearchBar.component.tsx
the text is not visible in the dark mode
<img width="332" alt="image" src="https://github.com/rogerosha/fe-react-2024/assets/97438530/f20f8692-cf9d-4f66-aab3-f4376f38595b">

2024-06-07 10:12 UTC, KPIcoder commented on src/components/theme/Theme.component.tsx
Usually contexts / providers are separated from the components. Move it to a separate file

2024-06-07 10:12 UTC, KPIcoder commented on src/pages/productsList/ProductsList.component.tsx
- Search and filtering are side effects of your component. Use the effect hook to listen to changes of their states
- Fix the category filtering function. It has to be multi select.

2024-06-11 02:09 UTC, rogerosha commented on src/pages/productsList/ProductsList.component.tsx
> * Fix the category filtering function. It has to be multi select.

when i created pr i checked this state and it was normal 🥺 

![image](https://github.com/rogerosha/fe-react-2024/assets/71977925/603a2c65-592f-4f4e-bb63-7653c1cbb6ef)

2024-07-16 17:33 UTC, merged